/*
 * Copyright 2022 Signal Messenger, LLC
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package org.signal.registration.sender.messagebird.classic;

import com.google.i18n.phonenumbers.PhoneNumberUtil;
import com.google.i18n.phonenumbers.Phonenumber;
import com.google.protobuf.InvalidProtocolBufferException;
import com.messagebird.MessageBirdClient;
import com.messagebird.exceptions.MessageBirdException;
import com.messagebird.objects.VoiceMessage;
import com.messagebird.objects.VoiceMessageResponse;
import io.micrometer.core.instrument.Timer;
import jakarta.inject.Singleton;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.Duration;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import org.signal.registration.sender.ApiClientInstrumenter;
import org.signal.registration.sender.AttemptData;
import org.signal.registration.sender.ClientType;
import org.signal.registration.sender.MessageTransport;
import org.signal.registration.sender.SenderIdSelector;
import org.signal.registration.sender.SenderRejectedRequestException;
import org.signal.registration.sender.UnsupportedMessageTransportException;
import org.signal.registration.sender.VerificationCodeGenerator;
import org.signal.registration.sender.VerificationCodeSender;
import org.signal.registration.sender.messagebird.MessageBirdClassicSessionData;
import org.signal.registration.sender.messagebird.MessageBirdExceptions;
import org.signal.registration.sender.messagebird.MessageBirdSenderConfiguration;
import org.signal.registration.util.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Sends messages through the MessageBird Voice API
 * <p>
 * The <a href="https://developers.messagebird.com/api/voice-messaging/#voice-messaging-api"> MessageBird Voice
 * Messaging API</a> sends arbitrary messages through voice calls. Verification codes are generated by this class and
 * added to the message text, then later verified through the previously stored session.
 */
@Singleton
public class MessageBirdVoiceSender implements VerificationCodeSender {

  private static final Logger logger = LoggerFactory.getLogger(MessageBirdVoiceSender.class);

  public static final String SENDER_NAME = "messagebird-voice";

  private final MessageBirdVoiceConfiguration configuration;
  private final VerificationCodeGenerator verificationCodeGenerator;
  private final MessageBirdVoiceTTSBodyProvider verificationTTSBodyProvider;
  private final MessageBirdClient client;
  private final ApiClientInstrumenter apiClientInstrumenter;
  private final SenderIdSelector senderIdSelector;

  public MessageBirdVoiceSender(
      final MessageBirdVoiceConfiguration configuration,
      final VerificationCodeGenerator verificationCodeGenerator,
      final MessageBirdVoiceTTSBodyProvider verificationTTSBodyProvider,
      final MessageBirdClient messageBirdClient,
      final ApiClientInstrumenter apiClientInstrumenter,
      final MessageBirdSenderConfiguration senderConfiguration) {
    this.configuration = configuration;
    this.verificationCodeGenerator = verificationCodeGenerator;
    this.verificationTTSBodyProvider = verificationTTSBodyProvider;
    this.client = messageBirdClient;
    this.apiClientInstrumenter = apiClientInstrumenter;
    this.senderIdSelector = new SenderIdSelector(senderConfiguration.senderIdsByRegion(), senderConfiguration.defaultSenderId());
  }

  @Override
  public String getName() {
    return SENDER_NAME;
  }

  @Override
  public Duration getAttemptTtl() {
    return this.configuration.sessionTtl();
  }

  @Override
  public boolean supportsTransport(final MessageTransport transport) {
    return transport == MessageTransport.VOICE;
  }

  @Override
  public boolean supportsLanguage(final MessageTransport messageTransport,
      final Phonenumber.PhoneNumber phoneNumber,
      final List<Locale.LanguageRange> languageRanges) {
    // the language is supported only if the upstream TTS API supports
    // it AND there's a translation for it
    return verificationTTSBodyProvider.supportsLanguage(languageRanges);
  }

  @Override
  public AttemptData sendVerificationCode(final MessageTransport messageTransport,
      final Phonenumber.PhoneNumber phoneNumber, final List<Locale.LanguageRange> languageRanges,
      final ClientType clientType) throws SenderRejectedRequestException {

    if (messageTransport != MessageTransport.VOICE) {
      throw new UnsupportedMessageTransportException();
    }

    final String e164 = PhoneNumberUtil.getInstance().format(phoneNumber, PhoneNumberUtil.PhoneNumberFormat.E164);

    final String verificationCode = verificationCodeGenerator.generateVerificationCode();
    final String body = verificationTTSBodyProvider.getVerificationBody(phoneNumber, clientType, verificationCode, languageRanges);

    final VoiceMessage request = new VoiceMessage(body, e164);
    request.setOriginator(senderIdSelector.getSenderId(phoneNumber));
    request.setRepeat(configuration.messageRepeatCount());
    verificationTTSBodyProvider.lookupMessageBirdLanguage(languageRanges).ifPresent(request::setLanguage);

    final Timer.Sample sample = Timer.start();

    try {
      final VoiceMessageResponse response = this.client.sendVoiceMessage(request);

      if (response.getRecipients().getTotalDeliveryFailedCount() != 0) {
        throw new SenderRejectedRequestException("Failed to deliver voice message");
      }

      apiClientInstrumenter.recordApiCallMetrics(
          getName(),
          "call.create",
          true,
          null,
          sample);

      return new AttemptData(
          Optional.of(response.getId()),
          MessageBirdClassicSessionData.newBuilder().setVerificationCode(verificationCode).build().toByteArray());
    } catch (final MessageBirdException e) {
      logger.debug("Failed verification with {}, errors={}", e.getMessage(), e.getErrors());

      apiClientInstrumenter.recordApiCallMetrics(
          getName(),
          "call.create",
          false,
          MessageBirdExceptions.extract(e),
          sample);

      throw MessageBirdExceptions.toSenderRejectedException(e)
          .orElseThrow(() -> new UncheckedIOException(new IOException(e)));
    } catch (final SenderRejectedRequestException | RuntimeException e) {
      logger.debug("Failed verification", e);

      apiClientInstrumenter.recordApiCallMetrics(
          getName(),
          "call.create",
          false,
          MessageBirdExceptions.extract(e),
          sample);

      throw e;
    }
  }

  @Override
  public boolean checkVerificationCode(final String verificationCode, final byte[] sessionData) {
    try {
      final String storedVerificationCode = MessageBirdClassicSessionData.parseFrom(sessionData).getVerificationCode();
      return Strings.equalsConstantTime(verificationCode, storedVerificationCode);
    } catch (final InvalidProtocolBufferException e) {
      logger.error("Failed to parse stored session data", e);
      throw new UncheckedIOException(e);
    }
  }
}
