//
// Copyright 2026 Asher Messenger contributors
// SPDX-License-Identifier: AGPL-3.0-only
//

//! The local mesh identity, derived from the account's ACI identity key pair
//! so the mesh fingerprint *is* the app's identity (`MeshIdentity_FromIdentityKeyPair`).
//!
//! The identity's signed prekey and Kyber prekey are generated by meshlink the
//! first time and then kept stable across launches by persisting the export
//! blob (`MeshIdentity_Export` / `MeshIdentity_Import`) in a KeyValueStore.
//! Both records are written into the app's ACI prekey stores under their ids
//! so a PreKeySignalMessage built from our card decrypts with the normal
//! `signalDecryptPreKey` path.

import Foundation
public import LibSignalClient

public final class MeshIdentityManager {
    public static let shared = MeshIdentityManager()

    private let kvStore = KeyValueStore(collection: "MeshIdentity")
    private enum Keys {
        static let identityExport = "identityExport"
        static let cardBase64 = "cardBase64"
        static let fingerprint = "fingerprint"
    }

    private let lock = NSLock()
    private var cachedIdentity: MeshIdentity?

    private init() {}

    // MARK: - Loading

    /// The identity, importing the persisted blob or deriving a new one from
    /// the ACI identity key pair. Throws `MeshError.notRegistered` before
    /// registration.
    public func loadOrCreate(tx: DBWriteTransaction) throws -> MeshIdentity {
        lock.lock()
        if let cachedIdentity {
            lock.unlock()
            return cachedIdentity
        }
        lock.unlock()

        let identity: MeshIdentity
        if let blob = kvStore.getData(Keys.identityExport, transaction: tx) {
            do {
                identity = try MeshIdentity.import(blob)
            } catch {
                // A blob from an older bridge that no longer decodes: rebuild.
                // The fingerprint stays the same (same identity key); only the
                // prekeys change, which is harmless for contacts that have not
                // started a session yet and forces a fresh PreKey message otherwise.
                Logger.warn("Mesh identity blob failed to import (\(error)); regenerating")
                identity = try createFromAccount(tx: tx)
            }
        } else {
            identity = try createFromAccount(tx: tx)
        }

        try storePreKeys(of: identity, tx: tx)
        try cacheCardMetadata(of: identity, tx: tx)

        lock.lock()
        cachedIdentity = identity
        lock.unlock()
        return identity
    }

    /// Whatever `loadOrCreate` produced earlier in this process, if anything.
    public var identityIfLoaded: MeshIdentity? {
        lock.lock()
        defer { lock.unlock() }
        return cachedIdentity
    }

    private func createFromAccount(tx: DBWriteTransaction) throws -> MeshIdentity {
        let identityManager = DependenciesBridge.shared.identityManager
        let tsAccountManager = DependenciesBridge.shared.tsAccountManager
        guard
            let keyPair = identityManager.identityKeyPair(for: .aci, tx: tx),
            let registrationId = tsAccountManager.getRegistrationId(for: .aci, tx: tx)
        else {
            throw MeshError.notRegistered
        }
        let name = Self.localDisplayName(tx: tx)
        let identity = try MeshIdentity.fromIdentityKeyPair(
            keyPair.identityKeyPair.serialize(),
            registrationId: registrationId,
            name: name,
        )
        kvStore.setData(try identity.export(), key: Keys.identityExport, transaction: tx)
        Logger.info("Created mesh identity \(try identity.fingerprint().meshHex)")
        return identity
    }

    /// The name that travels in our card: the local profile's given name, or
    /// a neutral placeholder. Peers on the air can read it, so keep it short.
    private static func localDisplayName(tx: DBReadTransaction) -> String {
        let profile = SSKEnvironment.shared.profileManagerRef.localUserProfile(tx: tx)
        if let givenName = profile?.filteredGivenName, !givenName.isEmpty {
            return String(givenName.prefix(32))
        }
        return "Asher"
    }

    /// Writes the identity's signed + Kyber prekey records into the ACI
    /// stores. `INSERT OR REPLACE` keyed by id, so repeating this on every
    /// launch is idempotent and also clears any `replacedAt` the app's own
    /// prekey rotation may have stamped on them (which would otherwise let
    /// `cullPreKeys` remove them after the grace period).
    private func storePreKeys(of identity: MeshIdentity, tx: DBWriteTransaction) throws {
        let signed = try identity.signedPreKeyRecord()
        let kyber = try identity.kyberPreKeyRecord()
        let store = DependenciesBridge.shared.signalProtocolStoreManager.preKeyStore.forIdentity(.aci)
        store.upsertPreKeyRecord(signed.serialize(), keyId: signed.id, in: .signed, isOneTime: false, tx: tx)
        store.upsertPreKeyRecord(kyber.serialize(), keyId: kyber.id, in: .kyber, isOneTime: false, tx: tx)
    }

    private func cacheCardMetadata(of identity: MeshIdentity, tx: DBWriteTransaction) throws {
        let card = try MeshContactCard(bytes: try identity.cardBytes())
        kvStore.setString(try card.base64(), key: Keys.cardBase64, transaction: tx)
        kvStore.setData(try identity.fingerprint(), key: Keys.fingerprint, transaction: tx)
    }

    // MARK: - Restore from an encrypted backup

    /// The fingerprint this account would derive on its own, or nil before
    /// registration. Used to refuse a backup made by a different identity.
    public func accountDerivedFingerprint(tx: DBReadTransaction) -> Data? {
        let identityManager = DependenciesBridge.shared.identityManager
        let tsAccountManager = DependenciesBridge.shared.tsAccountManager
        guard
            let keyPair = identityManager.identityKeyPair(for: .aci, tx: tx),
            let registrationId = tsAccountManager.getRegistrationId(for: .aci, tx: tx)
        else {
            return nil
        }
        return try? MeshIdentity.fromIdentityKeyPair(
            keyPair.identityKeyPair.serialize(),
            registrationId: registrationId,
            name: "probe",
        ).fingerprint()
    }

    /// Installs an identity recovered with `MeshIdentity.fromBackup` as this
    /// device's mesh identity (export blob, prekeys, card metadata, cache).
    /// The node must be stopped. Throws when the account is registered and
    /// its own identity key would give a different fingerprint: the mesh
    /// fingerprint *is* the account identity, and a session with a foreign
    /// key could never decrypt with the app's ACI stores.
    public func install(_ identity: MeshIdentity, tx: DBWriteTransaction) throws {
        let fingerprint = try identity.fingerprint()
        if let derived = accountDerivedFingerprint(tx: tx), derived != fingerprint {
            throw MeshError.ffi("This backup belongs to a different identity (\(fingerprint.meshHex.prefix(16))…); this account's mesh fingerprint is \(derived.meshHex.prefix(16))…")
        }
        kvStore.setData(try identity.export(), key: Keys.identityExport, transaction: tx)
        try storePreKeys(of: identity, tx: tx)
        try cacheCardMetadata(of: identity, tx: tx)
        lock.lock()
        cachedIdentity = identity
        lock.unlock()
        Logger.info("Installed mesh identity \(fingerprint.meshHex) from backup")
    }

    // MARK: - Card for QR

    /// Our card as URL-safe base64 (what goes in the QR code). Prefers the
    /// running node's card (it reflects renames), then the persisted copy.
    public func cardBase64(tx: DBReadTransaction) -> String? {
        if let node = MeshNodeService.shared.nodeIfRunning,
           let bytes = try? node.cardBytes(),
           let card = try? MeshContactCard(bytes: bytes),
           let base64 = try? card.base64() {
            return base64
        }
        return kvStore.getString(Keys.cardBase64, transaction: tx)
    }

    /// Our card bytes, if the identity exists.
    public func cardBytes() -> Data? {
        if let identity = identityIfLoaded {
            return try? identity.cardBytes()
        }
        return nil
    }

    /// Our 16-byte fingerprint (persisted copy; nil before first start).
    public func fingerprint(tx: DBReadTransaction) -> Data? {
        kvStore.getData(Keys.fingerprint, transaction: tx)
    }

    /// Forgets the persisted identity (e.g. on unregister). The next start
    /// derives a fresh one with new prekeys.
    public func reset(tx: DBWriteTransaction) {
        kvStore.removeAll(transaction: tx)
        lock.lock()
        cachedIdentity = nil
        lock.unlock()
    }
}
